# Generated by Django 5.2.7 on 2026-07-27 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('novel', 'Roman'), ('story_series', 'Feuilleton'), ('collection', 'Recueil')], max_length=20, verbose_name='type')),
                ('language', models.CharField(choices=[('ht', 'Kreyòl'), ('fr', 'Français')], max_length=2, verbose_name='langue')),
                ('description', models.TextField(blank=True, verbose_name='présentation')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='seri/', verbose_name='couverture')),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminée'), ('paused', 'En pause')], default='ongoing', max_length=12, verbose_name='état')),
                ('reveal_titles', models.BooleanField(default=False, help_text='Décoché, le public voit « Epizòd 4 — 29 juillet » sans le titre.', verbose_name='révéler le titre des épisodes à venir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'série',
                'verbose_name_plural': 'séries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ht', models.CharField(max_length=60, verbose_name='nom en kreyòl')),
                ('name_fr', models.CharField(max_length=60, verbose_name='nom en français')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'thème',
                'verbose_name_plural': 'thèmes',
                'ordering': ['order', 'name_ht'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('poem', 'Poème'), ('quote', 'Citation'), ('story', 'Histoire'), ('novel', 'Roman'), ('news', 'Actualité'), ('opinion', 'Opinion')], max_length=12, verbose_name='type')),
                ('format', models.CharField(blank=True, choices=[('plain', 'Texte brut'), ('markdown', 'Markdown')], help_text='Laissé vide, déduit du type : brut pour la poésie, Markdown pour la prose.', max_length=10, verbose_name='format')),
                ('language', models.CharField(choices=[('ht', 'Kreyòl'), ('fr', 'Français')], help_text='La langue dans laquelle Florentz a écrit. Le texte est publié tel quel.', max_length=2, verbose_name="langue d'écriture")),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('body', models.TextField(help_text="Poésie : les retours à la ligne sont conservés tels quels. Entourez un mot d'astérisques *comme ceci* pour le mettre en or.", verbose_name='texte')),
                ('excerpt', models.TextField(blank=True, help_text='Laissé vide, généré depuis le texte.', verbose_name='extrait')),
                ('episode_no', models.PositiveIntegerField(blank=True, null=True, verbose_name="n° d'épisode")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=12, verbose_name='état')),
                ('published_at', models.DateTimeField(blank=True, help_text='Une date future programme la parution — le texte reste invisible jusque-là.', null=True, verbose_name='date de publication')),
                ('reading_time', models.PositiveIntegerField(default=0, verbose_name='durée de lecture (min)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='lectures')),
                ('available_as_frame', models.BooleanField(default=False, verbose_name='disponible en cadre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='corpus.series', verbose_name='série')),
                ('themes', models.ManyToManyField(blank=True, related_name='texts', to='corpus.theme')),
            ],
            options={
                'verbose_name': 'texte',
                'verbose_name_plural': 'textes',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='odyo/%Y/%m/', verbose_name='fichier audio')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='durée (secondes)')),
                ('waveform', models.JSONField(blank=True, help_text='Amplitudes normalisées, pour dessiner la piste côté site.', null=True, verbose_name="forme d'onde")),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='corpus.text', verbose_name='texte')),
            ],
            options={
                'verbose_name': 'version audio',
                'verbose_name_plural': 'versions audio',
            },
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['status', 'published_at'], name='corpus_text_status_257401_idx'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['language', 'kind'], name='corpus_text_languag_0704ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'episode_no'), name='unique_episode_per_series'),
        ),
    ]
