# Generated by Django 5.2.7 on 2026-07-29 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_index_gin_trigrammes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='episode_no',
            field=models.PositiveIntegerField(blank=True, help_text="Laissé vide hors série. Un prologue est l'épisode 1, pas l'épisode 0.", null=True, validators=[django.core.validators.MinValueValidator(1, 'La numérotation des épisodes commence à 1.')], verbose_name="n° d'épisode"),
        ),
    ]
